apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atm-python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CanDuru4/ATM-Python-Best-Beginner-Hack' # Replace with your repo
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 